apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
{{- /* ConfigMaps */ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-thermal-mon-config
  namespace: {{ .Values.namespace }}
data:
  telegraf.conf: |-
{{ .Files.Get "config/telegraf.conf" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-thermal-script
  namespace: {{ .Values.namespace }}
data:
  collect_thermal_metrics.sh: |
{{ .Files.Get "config/collect_thermal_metrics.sh" | indent 4 }}
